{
  "openapi": "3.0.1",
  "info": {
    "title": "devicelinks",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "login"
    },
    {
      "name": "user"
    },
    {
      "name": "department"
    },
    {
      "name": "common"
    }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "summary": "登录",
        "deprecated": false,
        "description": "",
        "tags": [
          "login"
        ],
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "description": "用户名",
            "required": true,
            "example": "admin",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "description": "密码，16位小写md5加密后的值",
            "required": true,
            "example": "7a57a5a743894a0e",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "expires_in": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    },
                    "success": {
                      "type": "boolean"
                    },
                    "token": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "expires_in",
                    "message",
                    "success",
                    "token"
                  ],
                  "$ref": "#/components/schemas/LoginResult"
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "expires_in": 7200,
                      "message": "login success",
                      "success": true,
                      "token": "eyJraWQiOiI0NTc0Nzk1NyIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwczovL2RldmljZWxpbmtzLmNuIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MzYyNDEwNDgsImlhdCI6MTczNjIzMzg0OH0.CcA60ZuKyDXhAHoNyYY5rrIniW4aNCYYCM5hgYf44BA6UGZAOTtbNxR_53VYKH81_mNcVkT7eaasychqb-k3n-pmF4sJr9982PVAFm16WxhWgmh2WktDSbz1yl9Vw2LXFgQYlcfcMPkc5MVF74qjdtuyLwTSqE9DV2n1CcJZ5qudJsYNvByhtc46b61eI1ff7a204kONphcaxUP-UKkKV3dwWWCpVeAY4T_p8kQfdXh8csZRikCPp6ZzDFiDu7mV-1Oy929XS4FDZCVUPKpwsSTSkVxgG3P_HAuLXmCAEofVfj7VY6qqC9VSbOs2fRM89yiYackEQzSDKgalM9PVcg"
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/logout": {
      "post": {
        "summary": "退出登录",
        "deprecated": false,
        "description": "",
        "tags": [
          "login"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": false,
            "example": "Bearer eyJraWQiOiI0NTc0Nzk1NyIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwczovL2RldmljZWxpbmtzLmNuIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MzYyNDEwNDgsImlhdCI6MTczNjIzMzg0OH0.CcA60ZuKyDXhAHoNyYY5rrIniW4aNCYYCM5hgYf44BA6UGZAOTtbNxR_53VYKH81_mNcVkT7eaasychqb-k3n-pmF4sJr9982PVAFm16WxhWgmh2WktDSbz1yl9Vw2LXFgQYlcfcMPkc5MVF74qjdtuyLwTSqE9DV2n1CcJZ5qudJsYNvByhtc46b61eI1ff7a204kONphcaxUP-UKkKV3dwWWCpVeAY4T_p8kQfdXh8csZRikCPp6ZzDFiDu7mV-1Oy929XS4FDZCVUPKpwsSTSkVxgG3P_HAuLXmCAEofVfj7VY6qqC9VSbOs2fRM89yiYackEQzSDKgalM9PVcg",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "null"
                    },
                    "additional": {
                      "type": "object",
                      "properties": {}
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data",
                    "additional"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": "SUCCESS",
                      "message": "success",
                      "data": null,
                      "additional": {}
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/user": {
      "post": {
        "summary": "新增用户",
        "deprecated": false,
        "description": "",
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "description": "用户名",
                    "type": "string"
                  },
                  "account": {
                    "description": "账号",
                    "type": "string"
                  },
                  "email": {
                    "description": "邮箱地址",
                    "type": "string"
                  },
                  "phone": {
                    "description": "手机号",
                    "type": "string"
                  },
                  "departmentId": {
                    "description": "所属部门ID",
                    "type": "string"
                  },
                  "activateMethod": {
                    "description": "激活方式",
                    "type": "string"
                  },
                  "mark": {
                    "description": "备注",
                    "type": "string"
                  }
                },
                "required": [
                  "username",
                  "account",
                  "activateMethod"
                ]
              },
              "example": "{\n    \"username\":\"恒宇少年\", // 用户名\n    \"account\":\"yuqiyu\", // 账号\n    \"email\":\"hengboy@minbox.org\", //邮箱地址\n    \"phone\":\"\", // 手机号\n    \"departmentId\":\"\", //所属部门ID\n    \"activateMethod\":\"SendUrlToEmail\", // 激活方式\n    \"mark\":\"\" //备注\n}"
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/User"
                    },
                    "additional": {
                      "type": "object",
                      "properties": {}
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data",
                    "additional"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": "SUCCESS",
                      "message": "success",
                      "data": {
                        "id": "c460883ac80b4f499cf8ec03432d5876",
                        "name": "恒宇少年",
                        "account": "yuqiyu",
                        "email": "hengboy@minbox.org",
                        "phone": null,
                        "pwd": null,
                        "activateMethod": null,
                        "activateToken": "d414lY14kiEHNIVBZ_ysYplE5hGrKLqJWcyxBZdZ_SXQ2zY6Uo",
                        "departmentId": "cb4ad62ad53911efa7700242c0a8d704",
                        "identity": "User",
                        "lastLoginTime": null,
                        "lastChangePwdTime": null,
                        "enabled": false,
                        "deleted": false,
                        "createBy": "c31377a505e14fd2b52da54486ccaa4e",
                        "createTime": "2025-01-21T14:49:58.78654",
                        "mark": null
                      },
                      "additional": {}
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "get": {
        "summary": "分页查询用户",
        "deprecated": false,
        "description": "",
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "name": "pageSize",
            "in": "query",
            "description": "每页条数",
            "required": false,
            "example": "10",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "当前页码",
            "required": false,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sortProperty",
            "in": "query",
            "description": "排序属性，接口返回值\"result\"中的属性都可以作为排序字段",
            "required": false,
            "example": "createTime",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sortDirection",
            "in": "query",
            "description": "排序顺序，ASC：正序；DESC：倒序",
            "required": false,
            "example": "DESC",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "properties": {
                        "page": {
                          "type": "integer",
                          "description": "当前页码"
                        },
                        "pageSize": {
                          "type": "integer",
                          "description": "每页条数"
                        },
                        "totalPages": {
                          "type": "integer",
                          "description": "总页数"
                        },
                        "totalRows": {
                          "type": "integer",
                          "description": "总条数"
                        },
                        "result": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/User"
                          },
                          "description": "用户列表"
                        }
                      },
                      "required": [
                        "page",
                        "pageSize",
                        "totalPages",
                        "totalRows",
                        "result"
                      ],
                      "type": "object"
                    },
                    "additional": {
                      "type": "object",
                      "properties": {}
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data",
                    "additional"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": "SUCCESS",
                      "message": "success",
                      "data": {
                        "page": 1,
                        "pageSize": 10,
                        "totalPages": 1,
                        "totalRows": 1,
                        "result": [
                          {
                            "id": "c460883ac80b4f499cf8ec03432d5876",
                            "name": "恒宇少年",
                            "account": "yuqiyu",
                            "email": "hengboy@minbox.org",
                            "phone": null,
                            "pwd": null,
                            "activateMethod": null,
                            "activateToken": "d414lY14kiEHNIVBZ_ysYplE5hGrKLqJWcyxBZdZ_SXQ2zY6Uo",
                            "departmentId": "cb4ad62ad53911efa7700242c0a8d704",
                            "identity": "User",
                            "lastLoginTime": null,
                            "lastChangePwdTime": null,
                            "enabled": true,
                            "deleted": false,
                            "createBy": "c31377a505e14fd2b52da54486ccaa4e",
                            "createTime": "2025-01-21T14:49:59",
                            "mark": null,
                            "departmentName": "测试部门"
                          }
                        ]
                      },
                      "additional": {}
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/user/{userId}": {
      "post": {
        "summary": "更新用户",
        "deprecated": false,
        "description": "",
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "用户ID",
            "required": true,
            "example": "2f6e6a0fab1e435997e9b5e8b3fd62c8",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "description": "用户名",
                    "type": "string"
                  },
                  "email": {
                    "description": "邮箱地址",
                    "type": "string"
                  },
                  "phone": {
                    "description": "手机号",
                    "type": "string"
                  },
                  "departmentId": {
                    "description": "所属部门ID",
                    "type": "string"
                  },
                  "mark": {
                    "description": "备注",
                    "type": "string"
                  }
                },
                "required": [
                  "username",
                  "email",
                  "phone",
                  "departmentId",
                  "mark"
                ]
              },
              "example": "{\n    \"username\":\"恒宇少年\", // 用户名\n    \"account\":\"yuqiyu\", // 账号\n    \"email\":\"hengboy@minbox.org\", //邮箱地址\n    \"phone\":\"\", // 手机号\n    \"departmentId\":\"\", //所属部门ID\n    \"activateMethod\":\"SendUrlToEmail\", // 激活方式\n    \"mark\":\"\" //备注\n}"
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/User"
                    },
                    "additional": {
                      "type": "object",
                      "properties": {}
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data",
                    "additional"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": "SUCCESS",
                      "message": "success",
                      "data": {
                        "id": "c460883ac80b4f499cf8ec03432d5876",
                        "name": "恒宇少年",
                        "account": "yuqiyu",
                        "email": "hengboy@minbox.org",
                        "phone": null,
                        "pwd": null,
                        "activateMethod": null,
                        "activateToken": "d414lY14kiEHNIVBZ_ysYplE5hGrKLqJWcyxBZdZ_SXQ2zY6Uo",
                        "departmentId": "cb4ad62ad53911efa7700242c0a8d704",
                        "identity": "User",
                        "lastLoginTime": null,
                        "lastChangePwdTime": null,
                        "enabled": false,
                        "deleted": false,
                        "createBy": "c31377a505e14fd2b52da54486ccaa4e",
                        "createTime": "2025-01-21T14:49:58.78654",
                        "mark": null
                      },
                      "additional": {}
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "summary": "删除用户",
        "deprecated": false,
        "description": "",
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "用户ID",
            "required": true,
            "example": "2f6e6a0fab1e435997e9b5e8b3fd62c8",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/User"
                    },
                    "additional": {
                      "type": "object",
                      "properties": {}
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data",
                    "additional"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": "SUCCESS",
                      "message": "success",
                      "data": {
                        "id": "c460883ac80b4f499cf8ec03432d5876",
                        "name": "恒宇少年",
                        "account": "yuqiyu",
                        "email": "hengboy@minbox.org",
                        "phone": null,
                        "pwd": null,
                        "activateMethod": null,
                        "activateToken": "d414lY14kiEHNIVBZ_ysYplE5hGrKLqJWcyxBZdZ_SXQ2zY6Uo",
                        "departmentId": "cb4ad62ad53911efa7700242c0a8d704",
                        "identity": "User",
                        "lastLoginTime": null,
                        "lastChangePwdTime": null,
                        "enabled": false,
                        "deleted": false,
                        "createBy": "c31377a505e14fd2b52da54486ccaa4e",
                        "createTime": "2025-01-21T14:49:58.78654",
                        "mark": null
                      },
                      "additional": {}
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/user/status/{userId}": {
      "post": {
        "summary": "启用 / 禁用",
        "deprecated": false,
        "description": "",
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "用户ID",
            "required": true,
            "example": "2f6e6a0fab1e435997e9b5e8b3fd62c8",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "enabled",
            "in": "query",
            "description": "启用true，禁用：false",
            "required": false,
            "example": "true",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "null"
                    },
                    "additional": {
                      "type": "object",
                      "properties": {}
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data",
                    "additional"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": "SUCCESS",
                      "message": "success",
                      "data": null,
                      "additional": {}
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/user/me": {
      "get": {
        "summary": "获取登录人信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string",
                      "description": "状态码"
                    },
                    "message": {
                      "type": "string",
                      "description": "消息"
                    },
                    "data": {
                      "properties": {
                        "user": {
                          "$ref": "#/components/schemas/User"
                        },
                        "department": {
                          "$ref": "#/components/schemas/Department"
                        }
                      },
                      "required": [
                        "user",
                        "department"
                      ],
                      "$ref": "#/components/schemas/CurrentUser"
                    },
                    "additional": {
                      "type": "object",
                      "properties": {}
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data",
                    "additional"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": "SUCCESS",
                      "message": "success",
                      "data": {
                        "user": {
                          "id": "c31377a505e14fd2b52da54486ccaa4e",
                          "name": "admin",
                          "account": "admin",
                          "email": "master@devicelinks.cn",
                          "phone": "17111111111",
                          "pwd": null,
                          "activateMethod": null,
                          "activateToken": "0go2lQOwkLXfUFbTJuhynm9GfecaW4L8vulA4AcVE8Tk2UhlvD",
                          "departmentId": "cb4ad62ad53911efa7700242c0a8d704",
                          "identity": "SystemAdmin",
                          "lastLoginTime": null,
                          "lastChangePwdTime": null,
                          "enabled": true,
                          "deleted": false,
                          "createBy": null,
                          "createTime": "2024-12-09T11:15:43",
                          "mark": null
                        },
                        "department": {
                          "id": "cb4ad62ad53911efa7700242c0a8d704",
                          "name": "测试部门",
                          "identifier": "0001",
                          "pid": null,
                          "sort": 0,
                          "level": 1,
                          "deleted": false,
                          "createBy": null,
                          "createTime": "2025-01-18T09:16:07",
                          "description": null
                        }
                      },
                      "additional": {}
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/department": {
      "post": {
        "summary": "新增部门",
        "deprecated": false,
        "description": "",
        "tags": [
          "department"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "名称"
                  },
                  "identifier": {
                    "type": "string",
                    "description": "标识"
                  },
                  "pid": {
                    "type": "string",
                    "description": "上级部门ID"
                  },
                  "sort": {
                    "type": "integer",
                    "description": "排序"
                  },
                  "level": {
                    "type": "integer",
                    "description": "等级"
                  },
                  "description": {
                    "type": "string",
                    "description": "描述"
                  }
                },
                "required": [
                  "identifier",
                  "name"
                ]
              },
              "example": {
                "name": null,
                "identifier": null,
                "pid": null,
                "sort": 0,
                "level": 0,
                "description": null
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/department/{departmentId}": {
      "post": {
        "summary": "更新部门",
        "deprecated": false,
        "description": "",
        "tags": [
          "department"
        ],
        "parameters": [
          {
            "name": "departmentId",
            "in": "path",
            "description": "部门ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "名称"
                  },
                  "pid": {
                    "type": "string",
                    "description": "上级ID"
                  },
                  "sort": {
                    "type": "integer",
                    "description": "排序"
                  },
                  "description": {
                    "type": "string",
                    "description": "描述"
                  }
                },
                "required": [
                  "name"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "summary": "删除部门",
        "deprecated": false,
        "description": "",
        "tags": [
          "department"
        ],
        "parameters": [
          {
            "name": "departmentId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "23e5ab0237d047b8b6a969c070d2612e",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "get": {
        "summary": "获取信息",
        "deprecated": false,
        "description": "",
        "tags": [
          "department"
        ],
        "parameters": [
          {
            "name": "departmentId",
            "in": "path",
            "description": "部门ID",
            "required": true,
            "example": "23e5ab0237d047b8b6a969c070d2612e",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Department"
                    },
                    "additional": {
                      "type": "object",
                      "properties": {}
                    }
                  },
                  "required": [
                    "code",
                    "message",
                    "data",
                    "additional"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "code": "SUCCESS",
                      "message": "success",
                      "data": {
                        "id": "23e5ab0237d047b8b6a969c070d2612e",
                        "name": "测试部门002",
                        "identifier": "test",
                        "pid": null,
                        "sort": 0,
                        "level": 0,
                        "deleted": true,
                        "createBy": "c31377a505e14fd2b52da54486ccaa4e",
                        "createTime": "2025-01-23T14:04:49",
                        "description": "描述"
                      },
                      "additional": {}
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/common/search/field": {
      "get": {
        "summary": "查询检索字段",
        "deprecated": false,
        "description": "",
        "tags": [
          "common"
        ],
        "parameters": [
          {
            "name": "module",
            "in": "query",
            "description": "功能模块，取值：Device、User、Log、Notification",
            "required": false,
            "example": "User",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "请求令牌",
            "required": true,
            "example": "{{accessToken}}",
            "schema": {
              "type": "string",
              "default": "{{accessToken}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "field": {
                      "type": "string",
                      "description": "字段"
                    },
                    "fieldText": {
                      "type": "string",
                      "description": "字段中文描述"
                    },
                    "valueType": {
                      "type": "string",
                      "description": "字段值类型"
                    },
                    "componentType": {
                      "type": "string",
                      "description": "前端组件类型"
                    },
                    "optionDataSource": {
                      "type": "string",
                      "description": "下拉框选项数据源，STATIC：静态数据；API：接口查询数据"
                    },
                    "optionApiDataCode": {
                      "type": "null",
                      "description": "数据源为API时查询数据的编码"
                    },
                    "optionStaticData": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "label": {
                            "type": "string",
                            "description": "描述"
                          },
                          "value": {
                            "type": "string",
                            "description": "取值"
                          }
                        },
                        "required": [
                          "label",
                          "value"
                        ]
                      },
                      "description": "数据源为STATIC时的静态数据"
                    },
                    "operators": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "label": {
                            "type": "string",
                            "description": "描述"
                          },
                          "value": {
                            "type": "string",
                            "description": "运算符取值"
                          }
                        },
                        "required": [
                          "label",
                          "value"
                        ]
                      },
                      "description": "支持的运算法"
                    }
                  },
                  "required": [
                    "field",
                    "fieldText",
                    "valueType",
                    "componentType",
                    "optionDataSource",
                    "optionApiDataCode",
                    "optionStaticData",
                    "operators"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "field": "activateMethod",
                      "fieldText": "激活方式",
                      "valueType": "STRING",
                      "componentType": "SELECT",
                      "optionDataSource": "STATIC",
                      "optionApiDataCode": null,
                      "optionStaticData": [
                        {
                          "label": "向邮箱发送激活邮件",
                          "value": "SendUrlToEmail"
                        },
                        {
                          "label": "显示激活链接",
                          "value": "ShowUrl"
                        }
                      ],
                      "operators": [
                        {
                          "label": "等于",
                          "value": "EqualTo"
                        },
                        {
                          "label": "不等于",
                          "value": "NotEqualTo"
                        }
                      ]
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "LoginResult": {
        "type": "object",
        "properties": {
          "expires_in": {
            "type": "number",
            "description": "过期时间"
          },
          "message": {
            "type": "string",
            "description": "消息"
          },
          "success": {
            "type": "boolean",
            "description": "是否成功"
          },
          "token": {
            "type": "string",
            "description": "认证token"
          }
        },
        "title": "登录数据模型"
      },
      "PageResult": {
        "type": "object",
        "properties": {
          "page": {
            "type": "integer",
            "description": "当前页码"
          },
          "pageSize": {
            "type": "integer",
            "description": "每页条数"
          },
          "totalPages": {
            "type": "integer",
            "description": "总页数"
          },
          "totalRows": {
            "type": "integer",
            "description": "总条数"
          },
          "result": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "用户列表"
          }
        },
        "required": [
          "page",
          "pageSize",
          "totalPages",
          "totalRows",
          "result"
        ],
        "title": "分页数据模型"
      },
      "Department": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "ID"
          },
          "name": {
            "type": "string",
            "description": "部门名称"
          },
          "identifier": {
            "type": "string",
            "description": "标识符"
          },
          "pid": {
            "type": "string",
            "description": "上级ID",
            "nullable": true
          },
          "sort": {
            "type": "integer",
            "description": "排序"
          },
          "level": {
            "type": "integer",
            "description": "等级"
          },
          "deleted": {
            "type": "boolean",
            "description": "是否删除"
          },
          "createBy": {
            "type": "string",
            "description": "创建人ID",
            "nullable": true
          },
          "createTime": {
            "type": "string",
            "description": "创建时间"
          },
          "description": {
            "type": "string",
            "description": "描述",
            "nullable": true
          }
        },
        "required": [
          "id",
          "name",
          "identifier",
          "pid",
          "sort",
          "level",
          "deleted",
          "createBy",
          "createTime",
          "description"
        ],
        "title": "部门数据模型"
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "ID"
          },
          "name": {
            "type": "string",
            "description": "名称"
          },
          "account": {
            "type": "string",
            "description": "账号"
          },
          "email": {
            "type": "string",
            "description": "邮箱地址"
          },
          "phone": {
            "type": "string",
            "description": "手机号"
          },
          "pwd": {
            "type": "string",
            "description": "密码",
            "nullable": true
          },
          "activateMethod": {
            "type": "string",
            "description": "激活方式，SendUrlToEmail：向邮箱发送激活链接；ShowUrl：显示激活链接",
            "nullable": true
          },
          "activateToken": {
            "type": "string",
            "description": "记录令牌",
            "nullable": true
          },
          "departmentId": {
            "type": "string",
            "description": "所属部门ID",
            "nullable": true
          },
          "identity": {
            "type": "string",
            "description": "身份，User：普通用户；SystemAdmin：系统管理员；TenantAdmin：租户管理员"
          },
          "lastLoginTime": {
            "type": "string"
          },
          "lastChangePwdTime": {
            "type": "string"
          },
          "enabled": {
            "type": "boolean",
            "description": "是否启用"
          },
          "deleted": {
            "type": "boolean",
            "description": "是否删除"
          },
          "createBy": {
            "type": "string",
            "description": "创建人",
            "nullable": true
          },
          "createTime": {
            "type": "string",
            "description": "创建时间"
          },
          "mark": {
            "type": "string",
            "description": "备注",
            "nullable": true
          }
        },
        "required": [
          "id",
          "name",
          "account",
          "email",
          "phone",
          "activateMethod",
          "activateToken",
          "departmentId",
          "identity",
          "lastLoginTime",
          "lastChangePwdTime",
          "enabled",
          "deleted",
          "createBy",
          "createTime",
          "mark"
        ],
        "description": "用户信息",
        "title": "用户"
      },
      "SearchField": {
        "type": "object",
        "properties": {
          "searchFieldModule": {
            "type": "string",
            "description": "检索字段模块，User/Device/Log/Notification"
          },
          "searchMatch": {
            "type": "string",
            "description": "检索字段之间的匹配方式，ALL：所有；ANY：任意"
          },
          "searchFields": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "field": {
                  "type": "string",
                  "description": "检索字段"
                },
                "operator": {
                  "type": "string",
                  "description": "检索运算符，详见检索字段列表接口返回值"
                },
                "value": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "integer"
                      }
                    ]
                  },
                  "description": "匹配检索值列表"
                }
              },
              "required": [
                "field",
                "operator",
                "value"
              ]
            },
            "description": "检索字段列表"
          }
        },
        "required": [
          "searchMatch",
          "searchFieldModule"
        ],
        "title": "检索字段查询实体"
      },
      "CurrentUser": {
        "type": "object",
        "properties": {
          "user": {
            "$ref": "#/components/schemas/User"
          },
          "department": {
            "$ref": "#/components/schemas/Department"
          }
        },
        "required": [
          "user",
          "department"
        ],
        "title": "当前登录用户信息"
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [
    {
      "url": "http://localhost:8000/dev",
      "description": "本地研发"
    }
  ],
  "security": [
    {
      "bearer": []
    }
  ]
}